#include<iostream>
#include<stdlib.h>
#include"MyStack.h"
using namespace std;
int main()
{
	int x,i;
	cout<<"creating stack1 of size 10...."<<endl;
	MyStack s1(10);
	cout<<"pop from stack1...."<<endl;
	s1.Pop(x);
	cout<<"push 1 into stack1...."<<endl;
	s1.Push(1);
	cout<<"push 2 into stack1...."<<endl;
	s1.Push(2);
	cout<<"get maximum size of stack1...."<<endl;
	cout<<s1.GetMaxSize()<<endl;
	cout<<"creating stack2 of size 4...."<<endl;
	MyStack s2(4);
	cout<<"creating stack3 of size 8...."<<endl;
	MyStack s3(8);
	cout<<"creating stack4 of size 2...."<<endl;
	MyStack s4(2);
	cout<<"push 5 into stack2,stack3,stack4...."<<endl;
	s2.Push(5);
	s3.Push(5);
	s4.Push(5);
	cout<<"push 10 into stack4...."<<endl;
	s4.Push(10);
	cout<<"pop from stack2...."<<endl;
	s2.Pop(x);
	cout<<"push 4 into stack1...."<<endl;
	s1.Push(4);
	cout<<"push 2 into stack1...."<<endl;
	s1.Push(2);
	cout<<"push 23 into stack3...."<<endl;
	s3.Push(23);
	cout<<"push 5 into stack1...."<<endl;
	s1.Push(5);
	cout<<"push 4 into stack1...."<<endl;
	s1.Push(4);
	cout<<"push 78 into stack1...."<<endl;
	s1.Push(78);
	cout<<"push 3334 into stack2...."<<endl;
	s2.Push(3334);
	cout<<"push 1 into stack2...."<<endl;
	s2.Push(1);
	cout<<"push 0 into stack3...."<<endl;
	s3.Push(0);
	cout<<"push -5 into stack4...."<<endl;
	s4.Push(-5);
	cout<<"popped element is "<<x<<endl;
	cout<<"pop from stack3...."<<endl;
	s3.Pop(x);
	cout<<"pop from stack4...."<<endl;
	s4.Pop(x);
	cout<<"popped element is "<<x<<endl;
	cout<<"pop from stack3...."<<endl;
	s3.Pop(x);
	cout<<"pop from stack4...."<<endl;
	s4.Pop(x);
	cout<<"push 15 into stack4...."<<endl;
	s4.Push(15);
	cout<<"display stack4...."<<endl;
	s4.Display();
	cout<<"display stack3...."<<endl;
	s3.Display();
	cout<<"display stack2...."<<endl;
	s2.Display();
	cout<<"display stack1...."<<endl;
	s1.Display();
	cout<<"creating stack5 of size 10 from stack1 using copy constructor...."<<endl;
	MyStack s5(s1);
	cout<<"display stack5...."<<endl;
	s5.Display();
	cout<<"creating stack6 of size 10 from stack1 using '=' operator...."<<endl;
	MyStack s6=s1;
	cout<<"display stack6...."<<endl;
	s6.Display();
	return 0;
}
